---
- hosts: all
  become: yes
  user: vagrant
  vars:
    timezone: UTC
    locale: en_US.UTF-8
  tasks:
    - name: Set timezone to {{ timezone }}
      timezone:
        name: "{{ timezone }}"

    - name: Selinux set permissive mode
      selinux:
        policy: targeted
        state: permissive

    - name: Set default locale
      lineinfile: dest=/etc/locale.conf
        regexp="LC_ALL"
        line="LC_ALL=\"{{ locale }}\""

    - name: Add Docker repository
      shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install repos
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - epel-release

    - name: Install packages
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - wget
          - docker-ce
          - docker-compose
          - git

    - name: Enable and start docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Creating environment variable via file in /etc/profile.d
      shell: |
        echo "export LC_ALL=\"en_US.UTF-8\"" > python.sh
        echo "export PATH=\"$PATH:/usr/local/bin\"" >> python.sh
      args:
        chdir: /etc/profile.d